config/routes.rb
NewApp::Application.routes.draw do

  

  resources :students do
    
    member do
      
        get "do_query"
      
    end

    collection do
      
        get "do_queries"
        get "results"
      
    end
  end

  resources :colleges do
    member do
      get "search"
    end
    collection do
      get "results"
    end
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  	attr_accessible :chemistry, :dept, :maths, :physics, :student_id, :year, :college_id, :extended_sid
  	validates :maths, :physics, :chemistry, allow_blank: true, :inclusion => {:in => 0..100, :message => "Incorrect Range please enter valid details" }
  	validates :dept, :college_id, :student_id, :year, :presence => true
  	validates :year, :inclusion => {:in => 1900..2016 , :message => "Incorrect Range please enter valid details"}
  	belongs_to :college 

  	before_create :updating_extended_sid
  	
    def updating_extended_sid
            sid = self.id*1
        	extended_id = sid.to_s<<"_"<<College.find(self.college_id)[:name][0,2]<<"_"<<self.college_id.to_s
        	self.extended_sid = extended_id
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students= Student.all
	end

	def show
		@s = Student.find(params[:id])
		@params = params
		
		respond_to do |format|
			format.json do
			    render json: @s.to_json
			end

			format.html do
			end
		end
	end

	def new
		@input_params = Student.new

  	end

  	def edit
  		@student = Student.find(params[:id])

  		respond_to do |format|
  			format.json do
  				render json: @student.to_json
  			end
  			format.html do
  			end
  		end
  	end

  	def update
  		Rails.logger.debug "Inside Update Method"
  		@student = Student.find(params[:id])
  		Rails.logger.debug "#{params}"
		Rails.logger.debug "updating the attributes of student :#{params.inspect}"
		
		Rails.logger.debug "inspecting dept of student :#{@student.attributes["dept"].inspect}"
		@student.update_attributes(:student_id => params[:student][:student_id], :dept => params[:student][:dept], :maths => params[:student][:maths], :physics => params[:student][:physics], :chemistry => params[:student][:chemistry], :year => params[:student][:year], :college_id => params[:student][:college_id])
		logger.debug "updating the attributes of student :#{@student.attributes.inspect}"
		if @student.save	
			redirect_to action: :show
		else
			render :edit
		end
  	end

  	def create
		@student = Student.new(:student_id => params[:student_id], :dept => params[:dept], :maths => params[:maths], :physics => params[:physics],:chemistry => params[:chemistry], :year => params[:year],:college_id => params[:college_id], :extended_sid => params[:extended_sid])
		respond_to do |format|
  			format.json do
  				render json: @student.to_json
  			end
  			format.html do
  			end
  		end

		if @student.save
	      redirect_to action: :index
	    else
	      render :new
	    end 
		@students = Student.all
  	end

  	def destroy
  		@student = Student.find(params[:id])
  		@student.destroy
  		redirect_to action: :index
  	end

  	def do_query
 	end

  	def do_queries
  		Rails.logger.debug "inside do_queries"
  		unless params["group"].nil?
  		
	  		student_hash = Student.all
	  		grouped_hash= group_by(student_hash)
	  		@@get_compare = params["compare"]
	  		@@get_total = params["total"]
	  		@@final_sorted_hash = sort_by(grouped_hash)

	  		if (params[compare] == "1")
	  			compare
	  		end
	  		if (params[total] == "1")
	  			total
	  		end

	  		redirect_to results_students_url
	  	end

  	end

  	def total
  		Rails.logger.debug "Inside Total"
  		get_show_total = params["total"]
		if(get_show_total == "1")
		# checking the user input and looping according to it
			student_hash = Student.all
			grouped_show_total_hash = student_hash.group_by { |h| h[:year] } # grouping student hash by year and storing in grouped_show_total_hash
			Rails.logger.debug "#{grouped_show_total_hash}"
			
			 # printing the head row of the table to show the sorted hash
			totalhash = {}
			grouped_show_total_hash.each_key { |key| 
				len = grouped_show_total_hash[key].length
				Rails.logger.debug "#{len.inspect}"
				maths_tot = 0
				physics_tot = 0
				chemistry_tot = 0
				arr = []
				for i in 0..len-1
					Rails.logger.debug "Inside for loop"
					maths_tot = maths_tot + grouped_show_total_hash[key][i][:maths]             # calculating the total maths marks
					physics_tot = physics_tot + grouped_show_total_hash[key][i][:physics]		# calculating the total physics marks
					chemistry_tot = chemistry_tot + grouped_show_total_hash[key][i][:chemistry]	# calculating the total chemistry marks
					Rails.logger.debug "#{maths_tot}"
					Rails.logger.debug "#{physics_tot}"
					Rails.logger.debug "#{physics_tot}"
				end
				
				arr.push({:year => key, :mathstot => maths_tot, :physicstot => physics_tot, :chemistrytot => chemistry_tot })
				totalhash[key] = arr
				 # printing the values in table format
				
			}
			Rails.logger.debug "#{totalhash}"
			@@total_hash = totalhash
				
		else()
			puts "Show Total =false"
		end

  	end
	
  	def compare
  		student_hash = Student.all
  		#Rails.logger.debug "#{student_hash}"
  		get_compare = params["compare"]
  		
			# taking user inputs for current year and past year
			
		get_current_year = 2016

		get_past_year = 2015

			# grouping the student hash by year
		grouped_hash = student_hash.group_by { |h| h[:year] }
			#Rails.logger.debug "#{grouped_hash}"
			# defining current year hash and past year hash separately
		current_hash = grouped_hash[get_current_year]
		Rails.logger.debug "current hash: "
		Rails.logger.debug "#{current_hash}"
		past_hash = grouped_hash[get_past_year]
		if(get_compare == "student_id")
			# grouping the current hash and past hash with year	 according to id   
			Rails.logger.debug "#{past_hash}" 
			Rails.logger.debug "Inside if condition on compare on with student_id"
			Rails.logger.debug "#{params["compareon"]}"
			group_current_hash = current_hash.group_by {|i| i[:student_id]}
			Rails.logger.debug "#{group_current_hash}"
			group_past_hash = past_hash.group_by {|j| j[:student_id]}
			Rails.logger.debug "#{group_past_hash}"
			
			# defining the final hash to which all the current , past, change hashes have to be pushed	
			final_hash = {}
					# looping through current and past hashes if key value matches
			group_current_hash.each_key{ |key|
				if (group_past_hash.key?(key) == true)
						
					group_past_hash.each_key { |i|
			 						
			 			if (key == i)
			 						
			 				arr = []
							arr.push(group_current_hash[key]) # pushing current hash to array
							arr.push(group_past_hash[i]) # pushing past hash to array
							change_maths = (((group_current_hash[key][0][:maths] - group_past_hash[key][0][:maths])*100.to_f)/group_past_hash[key][0][:maths]).round(2) # calculating change of maths
							change_physics = (((group_current_hash[key][0][:physics] - group_past_hash[key][0][:physics])*100.to_f)/group_past_hash[key][0][:physics]).round(2) # calculating change of physics
							change_chemistry = (((group_current_hash[key][0][:chemistry] - group_past_hash[key][0][:chemistry])*100.to_f)/group_past_hash[key][0][:chemistry]).round(2) # calculating change of chemistry
							change_hash = [{:change_maths => change_maths, :change_physics => change_physics, :change_chemistry => change_chemistry, :change=>"change"}]
							arr.push(change_hash) # pushing change hash to array
							final_hash[key] = arr
				
						end
					}
							
				else()

					change_maths = 100
					change_physics = 100
					change_chemistry = 100

					change_hash = [{:change_maths => change_maths, :change_physics => change_physics, :change_chemistry => change_chemistry, :change=>"change"}]
							
					arr = []
					arr.push(group_current_hash[key]) # pushing current hash to array
					arr.push([{:maths => 0, :physics => 0, :chemistry => 0, :year => get_past_year.to_i}]) # pushing past hash to array
					arr.push(change_hash) # pushing change hash to array
					final_hash[key] = arr

				end

			}

			Rails.logger.debug "#{final_hash}"
			@@final_compare_hash = final_hash
			Rails.logger.debug "final_compare_hash: "
		
		elsif
			Rails.logger.debug "Inside elsif"
			group_current_hash = current_hash.group_by {|i| i[:dept]}
			Rails.logger.debug "#{group_current_hash}"
			group_past_hash = past_hash.group_by {|j| j[:dept]}
			Rails.logger.debug "#{group_past_hash}"
			final_hash = {}
			
			group_current_hash.each_key{ |key|
				Rails.logger.debug "Inside group_current_hash"
				mathstotal = 0
				physicstotal = 0
				chemistrytotal = 0
				current_arr = []
				len = group_current_hash[key].length

				for i in 0..len-1
					mathstotal = mathstotal + group_current_hash[key][i][:maths]
					physicstotal = physicstotal + group_current_hash[key][i][:physics]
					chemistrytotal = chemistrytotal + group_current_hash[key][i][:chemistry]
				end
				current_arr.push([{:year => 2016, :mathstotal => mathstotal, :physicstotal => physicstotal, :chemistrytotal => chemistrytotal }])
				Rails.logger.debug "#{current_arr}"
				if (group_past_hash.key?(key) == true)
					group_past_hash.each_key{ |k|
						if (key == k)
							Rails.logger.debug "Inside group_past_hash"
							mathstotal = 0
							physicstotal = 0
							chemistrytotal = 0
							len = group_past_hash[k].length

							for i in 0..len-1
								mathstotal = mathstotal + group_past_hash[k][i][:maths]
								physicstotal = physicstotal + group_past_hash[k][i][:physics]
								chemistrytotal = chemistrytotal + group_past_hash[k][i][:chemistry]
							end
						end
					
					}
					current_arr.push([{:year => 2015, :mathstotal => mathstotal, :physicstotal => physicstotal, :chemistrytotal => chemistrytotal }])
					final_hash[key] = current_arr
					Rails.logger.debug "current_arr: "
					Rails.logger.debug "#{current_arr.inspect}"
					Rails.logger.debug "final_hash: "
					Rails.logger.debug "#{final_hash.inspect}"

				end
			}
			final_hash.each_key { |k|
				change_maths = (((final_hash[k][0][0][:mathstotal] - final_hash[k][1][0][:mathstotal])*100.to_f)/final_hash[k][1][0][:mathstotal]).round(2) # calculating change of maths
				change_physics = (((final_hash[k][0][0][:physicstotal] - final_hash[k][1][0][:physicstotal])*100.to_f)/final_hash[k][1][0][:physicstotal]).round(2) # calculating change of physics
				change_chemistry = (((final_hash[k][0][0][:chemistrytotal] - final_hash[k][1][0][:chemistrytotal])*100.to_f)/final_hash[k][1][0][:chemistrytotal]).round(2) # calculating change of chemistry
				change_hash = [{:change=>"change", :change_maths => change_maths, :change_physics => change_physics, :change_chemistry => change_chemistry}]
				final_hash[k].push(change_hash)
			}
			Rails.logger.debug "#{final_hash}"
			@@final_compare_hash = final_hash
			Rails.logger.debug "final_compare_hash: "
			
		end
  	end

  	def sort_by(grouped_hash)
  		Rails.logger.debug "inside Sort by"
  		Rails.logger.debug "#{params["sort"]}"
  		get_sort = params["sort"]

app/helpers/students_helper.rb
module StudentsHelper
	
end

app/views/students/create.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
</style>
</head>



<body>

<table style="width:100%">
  <tr>
    <td>Id</td>
    <td>Student_ID</td>
    <td>Department</td>
    <td>Maths</td>
    <td>Physics</td>
    <td>Chemistry</td>
    <td>Year</td>
    <td>College_ID</td>
  </tr>

  <% @student.each do |s| %>   
    <tr>
      <td> <%= s[:id] %></td>
      <td> <%= s[:student_id] %></td>
      <td> <%= s[:dept] %></td>
      <td> <%= s[:maths] %></td>
      <td> <%= s[:physics] %></td>
      <td> <%= s[:chemistry] %></td>
      <td> <%= s[:year] %></td>
      <td> <%= s[:college_id]%></td>
    </tr>
  <% end %>

</table>
<p><%= link_to "Create new Student", {:action => 'new' }%></p>



</body>
</html>

app/views/students/do_queries.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
	p.group{

		padding: 20px;
	}
	p.sort{
		padding: 20px;
	}
	p.compare{
		padding: 20px;
	}
	p.total{
		padding: 20px;
	}
</style>
</head>
<body>
	<form url: { action: = "results"}, method: :results>
		<p class = "group"><%= label_tag(:group, "Group By") %>	
		<%= select_tag(:group, options_for_select([['Id', 'student_id'], ['Year', 'year'], ['Department','dept']])) %><br></p>
		<p class = "sort"><%= label_tag(:sort, "Sort By") %>	
		<%= select_tag(:sort, options_for_select([['Maths', 'maths'], ['Physics', 'physics'], ['Chemistry','chemistry']])) %><br></p>
		<p class = "compare">
		<%= label_tag(:compare, "Should Compare") %>
		<%= select_tag(:compare, options_for_select([['Id', 'student_id'], ['Department', 'dept']])) %>
		</p>
		<p class = "total"><%= check_box_tag(:total) %>
		<%= label_tag(:total, "Show Total") %></p>
		<%= submit_tag "Submit" %>

	</form>
</body>
</html>

app/views/students/do_query.html.erb
<h1>Students#do_query</h1>
<p>Find me in app/views/students/do_query.html.erb</p>

app/views/students/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
    table, tr, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
</style>
</head>

<script src="https://code.jquery.com/jquery-3.0.0.min.js" integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        function editStudent() {    
            $.ajax({
               url: 'http://localhost:3000/students/' + $(".student-id").val() + 'edit',
               data: {},
               type: 'GET',
               error: function() {
                    debugger
                  $('#info').html('<p>An error has occurred</p>');
               },
               success: function(data) {
                var student = data;
                  var table = $("<table></table>");
                  var tr1 = $("<tr></tr>");
                  var td11 = $("<td></td>");
                  td11.text("ID");
                  tr1.append(td11);
                  var td12 = $("<td></td>");
                  td12.text("Department");
                  tr1.append(td12);
                  var td13 = $("<td></td>");
                  td13.text("Maths");
                  tr1.append(td13);
                  var td14 = $("<td></td>");
                  td14.text("Physics");
                  tr1.append(td14);
                  var td15 = $("<td></td>");
                  td15.text("Chemistry");
                  tr1.append(td15);

                  var tr2 = $("<tr></tr>");

                  var td1 = $("<td></td>");
                  td1.text(data["id"]);
                  tr2.append(td1);
                  var td2 = $("<td></td>");
                  td2.text(data["dept"]);
                  tr2.append(td2);
                  var td3 = $("<td></td>");
                  td3.text(data["maths"]);
                  tr2.append(td3);
                  var td4 = $("<td></td>");
                  td4.text(data["physics"]);
                  tr2.append(td4);
                  var td5 = $("<td></td>");
                  td5.text(data["chemistry"]);
                  tr2.append(td5);

                  table.append(tr1);
                  table.append(tr2);
                  $(".student-json").html(table);        
               }
            });

        }
    </script>
<% if @student.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
 
    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<body> 
  <%= form_for @student do |f| %>
    <%= f.label(:student_id, "Student Id") %>
    <%= f.text_field(:student_id) %><br>
    <%= f.label(:dept, "Department") %>
    <%= f.text_field(:dept) %><br>
    <%= f.label(:maths, "Maths") %>
    <%= f.text_field(:maths) %><br>
    <%= f.label(:physics, "Physics") %>
    <%= f.text_field(:physics) %><br>
    <%= f.label(:chemistry, "Chemistry") %>
    <%= f.text_field(:chemistry) %><br>
    <%= f.label(:year, "Year") %>
    <%= f.text_field(:year) %><br>
    <%= f.label(:college_id, "College Id") %>
    <%= f.text_field(:college_id) %><br>
    <%= submit_tag("Update") %>
  <% end %>

  <p>
    <input type="text" class="student-id"/>
    <a href="#" onclick = "editStudent()">load student as json</a>
    <div class="student-json">
    </div>
</p>
</body>
</html>

app/views/students/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
}
th {
    text-align: left;
    background-color:#00b38f
}

tr:nth-child(even){background-color: #99ffeb}
tr:hover{background-color:#d6d6c2}
</style>
</head>

<body>

<table style="width:100%">
	<caption><h2>List of Students</h2></caption>
  <tr>
  	<th>Id</th>
    <th>Student_ID</th>
    <th>Department</th>
    <th>Maths</th>
    <th>Physics</th>
    <th>Chemistry</th>
    <th>Year</th>
    <th>College_ID</th>
    <th>Extended Sid</th>
    <th colspan="2">Operations</th>
    
  </tr>

  <% @students.each do |s| %>   
    <tr>
	    <td> <%= link_to s[:id], student_path(s), method: :get %></td>
	    <td> <%= s[:student_id] %></td>
	    <td> <%= s[:dept] %></td>
	    <td> <%= s[:maths] %></td>
	    <td> <%= s[:physics] %></td>
	    <td> <%= s[:chemistry] %></td>
	    <td> <%= s[:year] %></td>
      <td> <%= s[:college_id] %></td>
      <td> <%= s[:extended_sid] %></td>
		<td><%= link_to image_tag("Edit_Icon_16.png"), edit_student_path(s), method: :get %></td>
		<td><%= button_to "Delete Student", student_path(s),method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>

</table>
<p><%= link_to "Create new Student", { action: "new" } %></p>
<p><%= link_to "Do Queries", { action: "do_queries" } %></p>

</body>
</html>

app/views/students/new.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
	p.one{
		padding: 10px;
	}
	p.two{
		padding: 10px;
	}
	p.three{
		padding: 10px;
	}
	p.four{
		padding: 10px;
	}
	p.five{
		padding: 10px;
	}
	p.six{
		padding: 10px;
	}
	p.seven{
		padding: 10px;
	}
	p.eight{
		padding: 10px;
	}
</style>
</head>

<script src="https://code.jquery.com/jquery-3.0.0.min.js" integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        function newStudent() {    
            $.ajax({
               url: 'http://localhost:3000/students/new/',
               data: {},
               type: 'GET',
               error: function() {
                    debugger
                  $('#info').html('<p>An error has occurred</p>');
               },
               success: function(data) {
                var student = data;
                  var table = $("<table></table>");
                  var tr1 = $("<tr></tr>");
                  var td1 = $("<td></td>");
                  td1.text(data["id"]);
                  tr1.append(td1);
                  var td2 = $("<td></td>");
                  td2.text(data["dept"]);
                  var td3 = $("<td></td>");
                  td3.text(data["maths"]);
                  tr1.append(td3);
                  
                  table.append(tr1);

                  $(".student-json").html(table);          
               }
            });

        }
    </script>

<body>
	<%= form_tag("/students", method: "post") do %>
	  <p class="one"><%= label_tag(:student_id, "Student Id") %>
	  <%= text_field_tag(:student_id) %><br></p>
	  <p class="two"><%= label_tag(:dept, "Department") %>
	  <%= text_field_tag(:dept) %><br></p>
	  <p class="three"><%= label_tag(:maths, "Maths") %>
	  <%= text_field_tag(:maths) %><br></p>
	  <p class="four"><%= label_tag(:physics, "Physics") %>
	  <%= text_field_tag(:physics) %><br></p>
	  <p class="five"><%= label_tag(:chemistry, "Chemistry") %>
	  <%= text_field_tag(:chemistry) %><br></p>
	  <p class="six"><%= label_tag(:year, "Year") %>
	  <%= text_field_tag(:year) %><br></p>
	  <p class="eight"><%= label_tag(:college_id, "College Id") %>
	  <%= text_field_tag(:college_id) %><br></p>
	  <p class="seven"><%= submit_tag("Submit") %></p>
<% end %>

<p>
    <input type="text" class="student-id"/>
    <a href="#" onclick = "newStudent()">load student as json</a>
    <div class="student-json">
    </div>
</p>

</body>
</html>

app/views/students/results.html.erb
<!DOCTYPE html>
<html>

<head>
	<style>
		table, th, td {
		    border: 1px solid black;
		    border-collapse: collapse;
		}
	</style>
</head>

<body>
	
	
	<table style="width:100%">
	<tr>
	  	<td>Id</td>
	    <td>Maths</td>
	    <td>Physics</td>
	    <td>Chemistry</td>
  	</tr>
	<% @finalhash.each do |k|  %>
	<tr>
		
		<td> <%= k[:id] %></td>
	    <td> <%= k[:maths] %></td>
	    <td> <%= k[:physics] %></td>
	    <td> <%= k[:chemistry] %></td>
	   
	</tr>
	<% end  %>
	<% @final_hash %>
	</table>

	<% if( @compare == "student_id" ) %>
	<body>
		<table style="width:100%">
		<tr>
		  	<th>Id</th>
		    <th>Maths</th>
		    <th>Physics</th>
		    <th>Chemistry</th>
	  	</tr>
		<% @final_hash.each do |k ,v|  %>
		<tr><td><%= k %></td></tr>
		<% if v.size > 1 %>
			<tr>
				<td> <%= @final_hash[k][0][0][:year] %></td>
			    <td> <%= @final_hash[k][0][0][:maths] %></td>
			    <td> <%= @final_hash[k][0][0][:physics] %></td>
			    <td> <%= @final_hash[k][0][0][:chemistry] %></td>
			   
			</tr>
			<tr>
				<td> <%= @final_hash[k][1][0][:year] %></td>
			    <td> <%= @final_hash[k][1][0][:maths] %></td>
			    <td> <%= @final_hash[k][1][0][:physics] %></td>
			    <td> <%= @final_hash[k][1][0][:chemistry] %></td>
			</tr>
			<tr>
				<td> <%= @final_hash[k][2][0][:change] %></td>
			    <td> <%= @final_hash[k][2][0][:change_maths] %></td>
			    <td> <%= @final_hash[k][2][0][:change_physics] %></td>
			    <td> <%= @final_hash[k][2][0][:change_chemistry] %></td>
			</tr>
			<% end %>
		<% end  %>
		</table>
		<% end %>
	</body>

	<% if( @compare == "dept" ) %>
	<body>
		<table style="width:100%">
		<tr>
		  	<th>Id</th>
		    <th>Maths</th>
		    <th>Physics</th>
		    <th>Chemistry</th>
	  	</tr>
		<% @final_hash.each do |k ,v|  %>
		<tr><td><%= k %></td></tr>
		<% if v.size > 1 %>
			<tr>
				<td> <%= @final_hash[k][0][0][:year] %></td>
			    <td> <%= @final_hash[k][0][0][:mathstotal] %></td>
			    <td> <%= @final_hash[k][0][0][:physicstotal] %></td>
			    <td> <%= @final_hash[k][0][0][:chemistrytotal] %></td>
			   
			</tr>
			<tr>
				<td> <%= @final_hash[k][1][0][:year] %></td>
			    <td> <%= @final_hash[k][1][0][:mathstotal] %></td>
			    <td> <%= @final_hash[k][1][0][:physicstotal] %></td>
			    <td> <%= @final_hash[k][1][0][:chemistrytotal] %></td>
			</tr>
			<tr>
				<td> <%= @final_hash[k][2][0][:change] %></td>
			    <td> <%= @final_hash[k][2][0][:change_maths] %></td>
			    <td> <%= @final_hash[k][2][0][:change_physics] %></td>
			    <td> <%= @final_hash[k][2][0][:change_chemistry] %></td>
			</tr>
			<% end %>
		<% end  %>
		</table>
		<% end %>
	</body>
	
	
	<body>
	<% if(@total == "1") %>
		<table style="width:100%">
		<tr>
		  	<th>Year</th>
		    <th>Maths Total</th>
		    <th>Physics Total</th>
		    <th>Chemistry Total</th>
	  	</tr>
			<tr>
				<td> <%= @totalhash[2016][0][:year] %></td>
			    <td> <%= @totalhash[2016][0][:mathstot] %></td>
			    <td> <%= @totalhash[2016][0][:physicstot] %></td>
			    <td> <%= @totalhash[2016][0][:chemistrytot] %></td>
			   
			</tr>
			<tr>
				<td> <%= @totalhash[2015][0][:year] %></td>
			    <td> <%= @totalhash[2015][0][:mathstot] %></td>
			    <td> <%= @totalhash[2015][0][:physicstot] %></td>
			    <td> <%= @totalhash[2015][0][:chemistrytot] %></td>
			</tr>
			
		</table>
	<% end %>
	</body>
<p><%= link_to "Back to Students", { action: "index" } %></p>

</body>
</html>