config/routes.rb
NewApp::Application.routes.draw do

  

  resources :students do
    
    member do
      
        get "do_query"
      
    end

    collection do
      
        get "do_queries"
        get "results"
      
    end
  end

  resources :colleges do
    member do
      get "search"
    end
    collection do
      get "results"
    end
  end

end

app/models/college.rb
class College < ActiveRecord::Base
  	attr_accessible :name, :year
  	 
  	validates :name, :length => {:maximum => 25}, :presence => true
  	validates :year, :length => {:minimum => 4}, :presence => true
  	has_many :students
  	before_update :update_extended_id
  	protected
  	def update_extended_id
  	Rails.logger.debug "Inside College update_extended_id method"
  		if self.name_changed?
  			Rails.logger.debug "Inside if loop"
  			Rails.logger.debug "#{name.inspect}"
  			student = Student.find_all_by_college_id(self.id)
  			Rails.logger.debug "#{student.inspect}"
  			student.each do |s|
  				s.extended_sid = s[:id].to_s<<"_"<<self.name[0,2]<<"_"<<(self.id).to_s
  				s.save
  			end
  		end
  	end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController

	def index
		@colleges = College.all
	end

	def show

	end

	def new
		@college = College.new
	end

	def edit
		@college = College.find(params[:id])
	end

	def create
		@college = College.new(:name => params[:name], :year => params[:year])
		
		if @college.save
	      redirect_to action: :index
	    else
	      render :new
	    end 
		@colleges = College.all
	end

	def update
		@college = College.find(params[:id])
		if @college.update_attributes(:name => params[:college][:name], :year => params[:college][:year])
			redirect_to action: :show
		else
			render :edit
		end
	end

	def destroy
  		@college = College.find(params[:id])
  		@college.destroy
  		redirect_to action: :index
  	end

  	def results
  		Rails.logger.debug "Inside results method"
  		result = College.pluck(:name)
  		Rails.logger.debug "#{result}"
  		Rails.logger.debug "#{params[:Search].to_s}"
  		len = result.size
  		search_array = []
  		for i in 0..len-1
  			Rails.logger.debug "Inside for loop"
  			result[i].downcase!
  			if result[i].include? params[:Search]
   				search_array.push(result[i])
			end
		end
		@array = search_array
  	end

  	def search
  		college = College.find(params[:id])
  		Rails.logger.error "params: " + params.inspect
  		@students = college.students
  		Rails.logger.error "students: " + @Student.inspect
  	end

end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/create.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
}
th {
    text-align: left;
}
</style>
</head>

<body>

<table style="width:100%">
  <caption><h2>List of Colleges</h2></caption>
  <tr>
    <th>Name</th>
    <th>Established Year</th>
    
    <th colspan="2">Operations</th>
    
  </tr>

  <% @colleges.each do |s| %>   
    <tr>
      <td> <%= link_to s[:id] %></td>
      <td> <%= s[:name] %></td>
      <td> <%= s[:year] %></td>
      
      <td> <%= link_to image_tag("Edit_Icon_32.png"), edit_college_path(s), method: :get  %></td>
      <td><%= button_to "Delete College", college_path(s),method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>

</table>
<p><%= link_to "Create new College", { action: "new" } %></p>

</body>
</html>

app/views/colleges/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
	p.one{
		padding: 10px;
	}
	p.two{
		padding: 10px;
	}
	p.three{
		padding: 10px;
	}
	
</style>
</head>
<body>
	<%= form_for @college do |f| %>
	  <p class="one"><%= f.label(:name, "College Name") %>
	  <%= f.text_field(:name) %><br></p>
	  <p class="two"><%= f.label(:year, "Established Year") %>
	  <%= f.text_field(:year) %><br></p>
	  <p class="three"><%= submit_tag("Submit") %></p>
<% end %>
</body>
</html>

app/views/colleges/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
}
th {
    text-align: left;
    height: 50px;
}
</style>
</head>

<body>
<form action = "/colleges/results" method = "get" style = "float:right" placeholder = "search" >
  <input type="search" name="Search" />
</form><br>
<table style="width:100%">
	<caption><h2>List of Colleges</h2></caption>
  <tr>
    <th>Id</th>
  	<th>Name</th>
    <th>Established Year</th>
    
    <th colspan="3">Operations</th>
  </tr>

  <% @colleges.each do |s| %>   
    <tr>
	    <td> <%= link_to s[:id], college_path(s) %></td>
	    <td> <%= s[:name] %></td>
	    <td> <%= s[:year] %></td>
      
      <td> <%= link_to image_tag("Edit_Icon_32.png"), edit_college_path(s), method: :get  %></td>
      <td><%= button_to "Delete College", college_path(s),method: :delete, data: { confirm: "Are you sure?" } %></td>
      <td> <%= link_to image_tag("psearch.png"), search_college_path(s) %></td>
    </tr>
  <% end %>

</table>
<p><%= link_to "Create new College", { action: "new" } %></p>

</body>
</html>

app/views/colleges/new.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
	p.one{
		padding: 10px;
	}
	p.two{
		padding: 10px;
	}
	p.three{
		padding: 10px;
	}

</style>
</head>
<body>
	<%= form_tag("/colleges", method: "post") do %>
	  <p class="one"><%= label_tag(:name, "College Name") %>
	  <%= text_field_tag(:name) %><br></p>
	  <p class="two"><%= label_tag(:year, "Established Year") %>
	  <%= text_field_tag(:year) %><br></p>
	  
	  <p class="three"><%= submit_tag("Submit") %></p>
<% end %>
</body>
</html>

app/views/colleges/results.html.erb
<%= @array%>

app/views/colleges/search.html.erb
<!DOCTYPE html>
<html>

<head>
	<style>
		table, th, td {
		    border: 1px solid black;
		    border-collapse: collapse;
		}
	</style>
</head>
<body>
	
	<table style="width:100%">
	<tr>
	    <td>Student ID</td>
	    <td>College ID</td>
	    <td>Department</td>
	    <td>Year</td>
  	</tr>
  	<% @students.each do |s| %>
	<tr>
		<td> <%= s[:student_id] %></td>
		<td> <%= s[:college_id] %></td> 
		<td> <%= s[:dept] %></td>
		<td> <%= s[:year] %></td>  
	</tr>
	<% end %>
	</table>
	<p><%= link_to "Back to Colleges", { action: "index" } %></p>

</body>
</html>

app/views/colleges/show.html.erb
<!DOCTYPE html>
<html>

<head>
	<style>
		table, th, td {
		    border: 1px solid black;
		    border-collapse: collapse;
		}
	</style>
</head>

<body>

	
	<% @s = College.find(params["id"]) %>
	
	<table style="width:100%">
	<tr>
	  	<td>Id</td>
	    <td>Name</td>
	    <td>Year</td>
	    
  	</tr>
	<tr>
	  	<td> <%= params[:id] %></td>
	    <td> <%= @s[:name] %></td>
	    <td> <%= @s[:year] %></td>
	    
	</tr>
	</table>
<p><%= link_to "Back to Colleges", { action: "index" } %></p>

</body>
</html>